---
config:
    ER:
        layoutDirection: LR
        fontSize: 12
    theme: default
---
erDiagram
    EMPLEADO ||--o| ADMINISTRADOR : puede_ser
    ADMINISTRADOR ||--|| ACCESO : define
    AUTOBUS ||--o{ VIAJE : participa_en
    RUTA ||--o{ VIAJE : organiza
    VIAJE ||--o{ BOLETO : genera
    VIAJE ||--o{ REPORTE : registra

    EMPLEADO {
        string id_empleado PK
        string nombre
        string usuario
        string contrasena_encriptada
    }

    ADMINISTRADOR {
        string id_admin PK
        string id_empleado FK
    }

    ACCESO {
        string id_acceso PK
        string id_admin FK
        string permiso_altas
        string permiso_bajas
        string permiso_modificaciones
        string interfaz_accedida
    }

    AUTOBUS {
        string id_autobus PK
        string numero_unidad
        string modelo
        int capacidad_total
        string placa
    }

    RUTA {
        string id_ruta PK
        string origen
        string destino
        float distancia_estimada
    }

    VIAJE {
        string id_viaje PK
        string id_ruta FK
        string id_autobus FK
        date fecha_salida
        string hora_salida
        float costo_base
        string nombre_cliente
        string telefono_cliente
        string correo_cliente
    }

    BOLETO {
        string id_boleto PK
        string id_viaje FK
        string numero_asiento
        float costo_final
    }

    REPORTE {
        string id_reporte PK
        string id_viaje FK
        string descripcion_incidencia
        date fecha_reporte
    }
