---
config:
    ER:
        layoutDirection: LR
        fontSize: 12
    theme: default
---
erDiagram
    CLIENTES ||--o{ RESERVACIONES : realiza
    USUARIOS ||--o{ RESERVACIONES : registra
    TERMINALES ||--o{ USUARIOS : asigna
    TERMINALES ||--o{ RESERVACIONES : mediante
    VIAJES ||--o{ RESERVACIONES : para
    LUGARES ||--o{ VIAJES : origen
    LUGARES ||--o{ VIAJES : destino

    CLIENTES {
        string id_cliente PK
        string nombre
        string apellido
        string correo
        string telefono
    }

    USUARIOS {
        string id_usuario PK
        string username UK
        string password_hash
        string id_terminal FK
        date fecha_contratacion
        string nombre
        string apellido
        string direccion
        string correo
        string numero
        string rfc
        string sueldo
    }

    TERMINALES {
        string id_terminal PK
        string nombre_terminal
        string direccion
        string codigo_postal
    }

    LUGARES {
        string id_lugar PK
        string nombre_lugar
        string codigo_postal
    }

    VIAJES {
        string id_viaje PK
        string id_lugar_origen FK
        string id_lugar_destino FK
        date fecha
        int km_recorrer
        string tiempo_estimado_llegada
        int cupos_totales
        int cupos_disponibles
        string horario
    }

    RESERVACIONES {
        string id_reservacion PK
        string id_cliente FK
        string id_viaje FK
        string id_usuario FK
        string id_terminal FK
        date fecha_reservacion
        int asientos
        string estado
    }
